### PR TITLE
Add PORT variable for newsroom

### PR DESCRIPTION
**Pull request by MarkLark86**

### CODE REVIEW

**Comment by MarkLark86** [comment]
@petrjasek This should fix the CI instances for Newsroom failing to build.
`-bash: line 104: PORT: unbound variable`.

**Comment by petrjasek** [comment]
@MarkLark86 where is that? `$PORT` should be set by honcho

**Comment by MarkLark86** [comment]
I'm not sure. As the fireq instance is failing to run after your change, with the aforementioned error

**Comment by petrjasek** [comment]
got it, https://github.com/superdesk/fireq/pull/53 should fix it

**Pull request closed without merging**
